version: 2
updates:
  # Dependabot only updates hashicorp GHAs, external GHAs are managed by internal tooling (TSCCR)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "hashicorp/*"
