# Continuous integration handling for GitHub Actions workflows
name: ci-github-actions

on:
  pull_request:
    paths:
      - .github/workflows/*.yml

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: 'stable'
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      # Ignore false positives with actions/download-artifact
      # Reference: https://github.com/actions/download-artifact#download-path-output
      - run: actionlint -ignore 'property "download-path" is not defined in object type {}'
