# Continuous integration handling for GitHub Actions workflows
name: ci-github-actions

on:
  pull_request:
    paths:
      - .github/workflows/*.yml

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 'stable'
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      # Ignore false positives with actions/download-artifact
      # Reference: https://github.com/actions/download-artifact#download-path-output
      - run: actionlint -ignore 'property "download-path" is not defined in object type {}'
