on:
  workflow_call:
    inputs:
      goreleaser-release-args:
        description: 'goreleaser release Arguments (e.g. --skip-validate)'
        required: false
        type: string
      release-notes:
        description: 'Enable release notes handling (must have previously uploaded artifact named "release-notes" with file "release-notes.txt")'
        required: false
        type: boolean
      setup-go-version:
        description: 'setup-go Go Version'
        required: false
        type: string
      setup-go-version-file:
        description: 'setup-go File From Which To Read Go Version'
        required: false
        type: string
      git-ref:
        description: 'branch, tag or SHA to checkout'
        required: false
        type: string
    secrets:
      gpg-private-key:
        description: 'GPG Private Key'
        required: true
      gpg-private-key-passphrase:
        description: 'GPG Private Key Passphrase'
        required: false

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.git-ref }}
          fetch-depth: 0
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ inputs.setup-go-version }}
          go-version-file: ${{ inputs.setup-go-version-file }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.gpg-private-key }}
          passphrase: ${{ secrets.gpg-private-key-passphrase }}
      - if: inputs.release-notes != true
        name: goreleaser release (without release notes)
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          args: release --clean ${{ inputs.goreleaser-release-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      - if: inputs.release-notes
        id: release-notes-download
        name: Release Notes Download
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: release-notes
          path: /tmp
      - if: inputs.release-notes
        name: goreleaser release (with release notes)
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          args: release --release-notes ${{ steps.release-notes-download.outputs.download-path }}/release-notes.txt --clean ${{ inputs.goreleaser-release-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
